"""A Rust-based ndarray library. """

from typing import List, Sequence

class Array:
    """N-dimensional array of float64 values."""
    
    def __init__(self, shape: Sequence[int], data: Sequence[float]) -> None:
        """Create array from shape and flat data list."""
        ...
    
    @staticmethod
    def zeros(shape: Sequence[int]) -> Array:
        """Create array filled with zeros."""
        ...
    
    @property
    def shape(self) -> List[int]:
        """Get the shape as a list."""
        ...
    
    def get(self, indices: Sequence[int]) -> float:
        """Get element at indices."""
        ...
    
    def tolist(self) -> List[float]:
        """Return data as flat list."""
        ...
    
    def sin(self) -> Array: ...
    def cos(self) -> Array: ...
    def exp(self) -> Array: ...
    def sqrt(self) -> Array: ...
    def clip(self, min: float, max: float) -> Array: ...
    
    def __add__(self, other: Array) -> Array: ...
    def __sub__(self, other: Array) -> Array: ...
    def __mul__(self, other: Array) -> Array: ...
    def __truediv__(self, other: Array) -> Array: ...
    def __neg__(self) -> Array: ...
    def __repr__(self) -> str: ...


class Generator:
    """Random number generator."""
    
    def __init__(self) -> None:
        """Create time-seeded generator."""
        ...
    
    @staticmethod
    def from_seed(seed: int) -> Generator:
        """Create generator with explicit seed."""
        ...
    
    def uniform(self, low: float, high: float, shape: Sequence[int]) -> Array: ...
    def standard_normal(self, shape: Sequence[int]) -> Array: ...
    def normal(self, mu: float, sigma: float, shape: Sequence[int]) -> Array: ...
    def randint(self, low: int, high: int, shape: Sequence[int]) -> List[int]: ...


def zeros(shape: Sequence[int]) -> Array:
    """Create array filled with zeros."""
    ...
